version: "3.9"

services:
  # ========== DB Service (Worker only) ==========
  db:
    image: testforccsa/final-v3:db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == core
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========== Generator Service (Manager) ==========
  generator:
    image: testforccsa/final-v3:generator
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      GENERATE_INTERVAL_SECONDS: 5
      PEAK_HOURS: "7,9;17,19"
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == edge
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  # ========== Backend API Service (Manager) ==========
  backend:
    image: testforccsa/final-v3:backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == core
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    # 移除 healthcheck

  # ========== Frontend Web Service (Manager) ==========
  frontend:
    image: testforccsa/final-v3:frontend
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == edge
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      # 移除 healthcheck

# ========== Volumes ==========
volumes:
  db_data:
    driver: local

# ========== Networks ==========
networks:
  appnet:
    driver: overlay

    attachable: true
